export type RootStackParamList = {
  Onboarding1: undefined;
  Onboarding2: undefined;
  SignIn: undefined;
  SignUp: undefined;
  HomeScreen: undefined;
  ForgotPassword: undefined;
  BookAppointment: { doctorName?: string };
  AboutUs: undefined;
  Notifications: undefined;
  Settings: undefined;
  HelpSupport: undefined;
  EditProfile: undefined;
  MedicalRecords: undefined;
  Nearby: undefined;
  ConsultDoctor: { issue: string };
  OTPScreen: { email: string };
  ResetPasswordScreen: { email: string };
  HealthDetails: undefined;
  Feedback: undefined;
  TermsOfUse: undefined;
  PrivacyPolicy: undefined;
  HealthConsent: undefined;
  DoctorProfile: { doctor: any };
};
